### ISSUE TITLE
Define / expand "TSS/App/Device attestation"

### ISSUE THREAD

**Issue by steven-bellock** [riscv-non-isa/riscv-security-model#22]
From https://github.com/riscv-non-isa/riscv-security-model/blob/8625adfaf993958f12784b8e3cd2a760b4086d6c/specification/src/chapter2.adoc?plain=1#L575-L576 In particular `TSS` is not defined.

**Comment by NicholasWoodIMG** [comment]
Fixed in this PR (deleted obsolete term "TSS"):

https://github.com/riscv-non-isa/riscv-security-model/pull/26
