### ISSUE TITLE
Description of measurement

### ISSUE THREAD

**Issue by steven-bellock** [riscv-non-isa/riscv-security-model#23]
The description of a measurement is too narrow. https://github.com/riscv-non-isa/riscv-security-model/blob/8625adfaf993958f12784b8e3cd2a760b4086d6c/specification/src/chapter2.adoc?plain=1#L744-L745 In particular a measurement is a reading of some past/present/future state of a system. Multiple states may be folded into a single measurement value, through, for example, a running hash, but a measurement could equally be a one-bit fuse value.

**Comment by NicholasWoodIMG** [comment]
Thanks,

I think Ravi's suggestion makes sense. Do you agree @steven-bellock.

I will prepare a PR.

**Comment by steven-bellock** [comment]
Yes, that sounds good.

**Comment by NicholasWoodIMG** [comment]
Addressed in this PR:

https://github.com/riscv-non-isa/riscv-security-model/pull/26/files
