### ISSUE TITLE
Address QCom review comments

### ISSUE THREAD

**Issue by NicholasWoodIMG** [riscv-non-isa/riscv-security-model#27]
[riscv-platform-security-model_qcom.pdf](https://github.com/riscv-non-isa/riscv-security-model/files/14483507/riscv-platform-security-model_qcom.pdf)

**Comment by NicholasWoodIMG** [comment]
Created a PR for fixes and clarifications from qcom comments:

https://github.com/riscv-non-isa/riscv-security-model/pull/26

**Comment by rsahita** [comment]
closing since the PR #26 was merged. 
cc @ozkoyuncu
