### ISSUE TITLE
Need to update this repo to new spec build method

### ISSUE THREAD

**Issue by rsahita** [riscv-non-isa/riscv-security-model#4]
@rpsene can you help? thanks

**Comment by rsahita** [comment]
I have sent a PR - ptal thanks

**Comment by rsahita** [comment]
thanks! (there was a minor error reported in terms of uploading the final pdf artifact) @rpsene

**Comment by rpsene** [comment]
@rsahita my fault, let me send a update pointing to the right location of the PDF file.

**Comment by rsahita** [comment]
thanks much!
